# Change these first
owner: SavageServices # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: AccountingPortal
    url: https://accounting.savageservices.com/accountingPortal/
  - name: Archiver
    url: https://archiver.savageservices.com/
  - name: Connect
    url: https://connect.savageservices.com
  - name: Input
    url: https://input.savageservices.com
  - name: S7i
    url: https://s7i.savageservices.com
  - name: Snapshot
    url: https://snapshot.savageservices.com
  - name: TheHub
    url: https://thehub.savageservices.com
  - name: TheHub2
    url: https://thehub2.savageservices.com
  - name: Trainloading
    url: https://trainloading.savageservices.com/train-loading/train/
  - name: Transload
    url: https://transload.savageservices.com


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.savageservices.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Savage Services Application **Status**"
  introMessage: Below are **real-time** uptime data
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
